Repository fsr5-fhaachen/strichlistensystem, pull requests merged in 2023-10, with the labels that each got.

#78 Export with special Characters
  app/Http/Controllers/ExportController.php
Labels: enhancement

#76 feat(deploy): add guide
  deploy/README.md
Labels: documentation, enhancement

#77 Implement portals import
  .env.example
  app/Http/Controllers/PortalsController.php
  app/Http/Middleware/Vpn.php
  app/Http/Middleware/VpnOrPerson.php
  app/Models/Person.php
  app/Utils/Telegram.php
  composer.json
  composer.lock
  database/migrations/2021_10_23_133727_create_persons_table.php
  database/migrations/2023_10_20_163214_update_img_in_persons_table.php
  public/js/app.js
  resources/js/Pages/App/Index.vue
  resources/js/app.js
  resources/js/components/PersonCard.vue
  routes/web.php
  tests/Feature/ExampleTest.php
Labels: enhancement

#79 fix(dockerfile): add pgsql driver
  Dockerfile
Labels: bug, enhancement

#80 fix(dockerfile): add pgsql
  Dockerfile
Labels: bug

#81 fix(dockerfile): pin roadrunner version
  Dockerfile
Labels: bug

#82 fix(config/database): redis cluster
  config/database.php
Labels: bug, enhancement

#83 fix(config/database): redis cluster
  config/database.php
Labels: bug

#85 fix: redis-cluster
  Dockerfile
  composer.lock
Labels: bug

#86 Add public url
  .env.example
  app/Models/Person.php
  config/app.php
Labels: enhancement

#88 merge dev to main
  .devcontainer/devcontainer.json
  .env.example
  Dockerfile
  README.md
  app/Http/Controllers/ExportController.php
  app/Http/Controllers/PortalsController.php
  app/Http/Middleware/Vpn.php
  app/Http/Middleware/VpnOrPerson.php
  app/Models/Person.php
  app/Utils/Telegram.php
  composer.json
  composer.lock
  config/app.php
  config/database.php
  database/migrations/2021_10_23_133727_create_persons_table.php
  database/migrations/2023_10_20_163214_update_img_in_persons_table.php
  deploy/README.md
  docker-compose.old.yml
  docker-compose.yml
  phpunit.xml
  public/js/app.js
  resources/js/Pages/App/Index.vue
  resources/js/app.js
  resources/js/components/PersonCard.vue
  routes/web.php
  tests/Feature/ExampleTest.php
Labels: bug, documentation, enhancement
