Repository fsr5-fhaachen/strichlistensystem, pull requests merged in 2024-10, with the labels that each got.

#101 feat: add article max_order_amount
  .env.example
  app/Http/Controllers/PersonController.php
  app/Models/Article.php
  database/migrations/2024_09_21_122430_add_max_order_amount_to_articles_table.php
  database/seeders/ArticleSeeder.php
  resources/js/components/ArticleCard.vue
Labels: enhancement

#120 Laravel 11.x Shift
  .env.example
  .github/workflows/ci.yml
  app/Console/Kernel.php
  app/Exceptions/Handler.php
  app/Http/Controllers/Controller.php
  app/Http/Kernel.php
  app/Http/Middleware/Authenticate.php
  app/Http/Middleware/EncryptCookies.php
  app/Http/Middleware/PreventRequestsDuringMaintenance.php
  app/Http/Middleware/RedirectIfAuthenticated.php
  app/Http/Middleware/TrimStrings.php
  app/Http/Middleware/TrustHosts.php
  app/Http/Middleware/TrustProxies.php
  app/Http/Middleware/ValidateSignature.php
  app/Http/Middleware/VerifyCsrfToken.php
  app/Models/User.php
  app/Providers/AppServiceProvider.php
  app/Providers/AuthServiceProvider.php
  app/Providers/BroadcastServiceProvider.php
  app/Providers/EventServiceProvider.php
  app/Providers/RouteServiceProvider.php
  artisan
  bootstrap/app.php
  bootstrap/providers.php
  composer.json
  composer.lock
  config/.gitkeep
  config/app.php
  config/auth.php
  config/broadcasting.php
  config/cache.php
  config/cors.php
  config/database.php
  config/filesystems.php
  config/hashing.php
  config/logging.php
  config/mail.php
  config/queue.php
  config/sanctum.php
  config/services.php
  config/session.php
  config/view.php
  docker-compose.old.yml
  phpunit.xml
  public/index.php
  routes/api.php
  routes/channels.php
  routes/console.php
  tests/CreatesApplication.php
  tests/TestCase.php
Labels: breaking-change, dependencies

#122 feat: use devcontainer and ci from portals
  .devcontainer/devcontainer.json
  .env.example
  .github/workflows/ci.yml
  .github/workflows/docker-dev.yml
  .github/workflows/docker-e2e.yaml
  .github/workflows/docker-release.yml
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  Dockerfile
  config/octane.php
  docker-compose.sail.yaml
  docker-compose.yaml
  tailwind.config.cjs
Labels: enhancement, github_actions

#146 feat: add APP_FORCE_HTTPS / feat: add article fassbrause
  .env.example
  app/Providers/AppServiceProvider.php
  config/app.php
  database/migrations/2024_10_27_140636_update_icon_in_articles_table.php
  database/seeders/ArticleSeeder.php
  database/seeders/DatabaseSeeder.php
  resources/js/app.js
Labels: enhancement, php

#139 Feat: Add new courses to portals importer
  app/Http/Controllers/PortalsController.php
Labels: enhancement

#150 fix: dynamic csv export
  app/Http/Controllers/ExportController.php
Labels: bug
